spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false
    encoding: UTF-8

  devtools:
    restart:
      enabled: true
      exclude: static/**,templates/**

  jade4j:
    caching: false

  jpa:
    show-sql: ${hibernate.show-sql}
    hibernate:
      ddl-auto: ${hibernate.ddl-auto}
      format-sql: ${hibernate.format-sql}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://${db.hostname}:${db.port}/${db.schema}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8
    username: ${db.username}
    password: ${db.password}

    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
info:
  component: This is REST API for Notarial Services.

#server:
#  port: 8080
#  servlet:
#    context-path:
logging:
  level:
    org.springframework.web: ERROR
    com.raysmond.blog: DEBUG